# Generated by Django 5.1 on 2024-08-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mookie', '0002_rename_uploaded_at_resume_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resume',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
